apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
- ../../base

patches:
- path: patches/deployment.yaml
  target:
    kind: Deployment
    name: sample-app

commonLabels:
  environment: dev

configMapGenerator:
- name: sample-app-config
  behavior: merge
  literals:
  - APP_ENV=development
  - LOG_LEVEL=debug 