apiVersion: v2
name: monitoring
description: Microservices Platform Monitoring Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "27.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  
  - name: grafana
    version: "8.10.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  
  - name: alertmanager
    version: "1.15.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: alertmanager.enabled 