server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  persistentVolume:
    enabled: true
    size: 8Gi
  service:
    type: NodePort
    nodePort: 30000

  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

  # アラートルールの設定を追加
  alertmanagerFiles:
    alertmanager.yml:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job', 'severity']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack'
        routes:
        - match:
            severity: critical
          receiver: 'slack'
          group_wait: 10s
      receivers:
      - name: 'slack'
        slack_configs:
        - send_resolved: true
          # Slack WebhookのURLは後で設定
          api_url: 'https://hooks.slack.com/services/your/webhook/url'
          channel: '#alerts'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
          text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

  # カスタムアラートルールの追加
  serverFiles:
    alerting_rules.yml:
      groups:
      - name: kubernetes-alerts
        rules:
        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.node }} is not ready"
            description: "Node {{ $labels.node }} has been in NotReady state for more than 5 minutes"
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) * 300 > 3
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is restarting {{ $value }} times / 5 minutes"
      - name: application-alerts
        rules:
        - alert: ApplicationUnhealthy
          expr: app_status == 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Application {{ $labels.instance }} is unhealthy"
            description: "Application instance {{ $labels.instance }} has been reporting unhealthy status for more than 2 minutes"
        - alert: HighLatency
          expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High latency detected for {{ $labels.path }}"
            description: "95th percentile latency is above 500ms for {{ $labels.path }}"
        - alert: HighErrorRate
          expr: rate(http_requests_total{status!="200"}[5m]) / rate(http_requests_total[5m]) * 100 > 5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High error rate for {{ $labels.path }}"
            description: "Error rate is above 5% for {{ $labels.path }}"

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  # Alertmanagerの設定
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack'
      routes:
      - match:
          severity: critical
        receiver: 'slack'
        group_wait: 10s
    receivers:
    - name: 'slack'
      slack_configs:
      - send_resolved: true
        # Slack WebhookのURLは後で設定
        api_url: 'https://hooks.slack.com/services/your/webhook/url'
        channel: '#alerts'
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

nodeExporter:
  enabled: true
  
pushgateway:
  enabled: true

kubeStateMetrics:
  enabled: true 