# グローバル設定
global:
  environment: dev
  domain: microservices.example.com

prometheus:
  enabled: true
  server:
    retention: 15d
    persistentVolume:
      size: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    alertmanagers:
      - static_configs:
          - targets:
              - "alertmanager-service.monitoring:9093"

grafana:
  enabled: true
  adminPassword: "changeme" # 本番環境では適切なパスワード管理が必要
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack'
    receivers:
      - name: 'slack'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX' # Slack Webhook URLを設定
            channel: '#alerts'
            send_resolved: true
  persistence:
    enabled: true
    size: 5Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534 