apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: microservices
  labels:
    app: sample-app
    environment: dev
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_PATH: "/" 