apiVersion: v2
name: logging
description: Microservices Platform Logging Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  
  - name: kibana
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: kibana.enabled
  
  - name: fluent-bit
    version: "0.48.10"
    repository: "https://fluent.github.io/helm-charts"
    condition: fluent-bit.enabled 