---
# SSHサービスの再起動
- name: restart sshd
  service:
    name: sshd
    state: restarted

# システムの再起動
- name: reboot system
  reboot:
    msg: "システムを再起動します"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime 