apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- sample-app/deployment.yaml
- sample-app/service.yaml
- sample-app/configmap.yaml

commonLabels:
  app.kubernetes.io/name: sample-app
  app.kubernetes.io/managed-by: kustomize 