# グローバル設定
global:
  environment: dev
  region: ap-northeast-1
  domain: microservices.example.com

# リソース制限のデフォルト値
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# 監視設定
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
  alertmanager:
    enabled: true

# ログ設定
logging:
  enabled: true
  elasticsearch:
    enabled: true
  fluentd:
    enabled: true
  kibana:
    enabled: true 