groups:
- name: application-alerts
  rules:
  # アプリケーションの状態監視
  - alert: ApplicationUnhealthy
    expr: app_status == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Application {{ $labels.instance }} is unhealthy"
      description: "Application instance {{ $labels.instance }} has been reporting unhealthy status for more than 2 minutes"

  # 高レイテンシーの監視
  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High latency detected for {{ $labels.path }}"
      description: "95th percentile latency is above 500ms for {{ $labels.path }}"

  # エラーレート監視
  - alert: HighErrorRate
    expr: rate(http_requests_total{status!="200"}[5m]) / rate(http_requests_total[5m]) * 100 > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High error rate for {{ $labels.path }}"
      description: "Error rate is above 5% for {{ $labels.path }}" 